export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const HEARTBEAT_UPDATED = "EVENT/HEARTBEAT_UPDATED";
export const DATA_NAME_RECEIVED = "EVENT/DATA_NAME_RECEIVED";
export const DATA_NAME_ADDED = "EVENT/DATA_NAME_ADDED"; 